"""What ``promptise mcpcast`` writes, and what it refuses to write over.

File ownership under ``tools/`` (the generated header decides), the renamed-package
refusal, the README's client snippets per auth mode, the render-time caps on tool
descriptions, Markdown escaping of plan text, identifier length and the CLI summary
line — each test treats the output the way a developer meets it.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from promptise.config import HTTPServerSpec, StdioServerSpec
from promptise.mcpcast import (
    MCPcastPlan,
    load_generated_server,
    mcpcast,
    render_project,
    render_readme,
    write_project,
)
from promptise.mcpcast.emit import (
    _GENERATED_MARKER,
    _MAX_DESCRIPTION_CHARS,
    _MAX_EXAMPLE_CHARS,
    _MAX_IDENT_CHARS,
    _MAX_PARAM_DESC_CHARS,
    _is_generated,
    _signature,
    _tool_description,
    clipped_descriptions,
    describe_written,
    python_identifier,
)
from promptise.mcpcast.schema import (
    ApprovalMode,
    AuthMode,
    DroppedOp,
    MCPcastError,
    ParamPlan,
    SafetyProfile,
)

SPEC = {
    "openapi": "3.0.0",
    "info": {"title": "Helpdesk API", "description": "Tickets and customers."},
    "servers": [{"url": "https://help.example/api"}],
    "paths": {
        "/tickets": {
            "get": {"operationId": "listTickets", "summary": "List tickets", "tags": ["tickets"]},
            "post": {
                "operationId": "createTicket",
                "summary": "Open a ticket",
                "tags": ["tickets"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "required": ["subject"],
                                "properties": {"subject": {"type": "string"}},
                            }
                        }
                    }
                },
            },
        },
        "/customers/{id}": {
            "get": {
                "operationId": "getCustomer",
                "summary": "Get a customer",
                "parameters": [
                    {"name": "id", "in": "path", "required": True, "schema": {"type": "string"}}
                ],
            }
        },
        "/v1/admin/purge": {"post": {"operationId": "purgeAll", "summary": "Purge everything"}},
    },
}


def _plan(**kw) -> MCPcastPlan:
    return mcpcast(SPEC, name="helpdesk", **kw)


def _snapshot(root: Path) -> dict[str, bytes]:
    """Every file under *root* with its content — to prove a refusal wrote nothing."""
    return {
        p.relative_to(root).as_posix(): p.read_bytes()
        for p in root.rglob("*")
        if p.is_file() and "__pycache__" not in p.parts
    }


def _many_tools_spec(tag: str, count: int) -> dict:
    """*count* GET operations under one tag — one tools module with a long docstring."""
    return {
        "openapi": "3.0.0",
        "info": {"title": "Warehouse"},
        "servers": [{"url": "https://wh.example"}],
        "paths": {
            f"/{tag}/kind-{i:03d}": {
                "get": {
                    "operationId": f"list{tag.title()}Kind{i:03d}",
                    "summary": f"List every {tag} record of kind {i}",
                    "tags": [tag],
                }
            }
            for i in range(count)
        },
    }


# ---------------------------------------------------------------------------
# Ownership under tools/: H8, L6, M13
# ---------------------------------------------------------------------------


class TestToolsOwnership:
    def test_hand_written_module_at_a_rendered_path_is_refused_untouched(self, tmp_path):
        out = tmp_path / "helpdesk-mcp"
        write_project(_plan(profile=SafetyProfile.READ_ONLY), out)  # no admin group yet
        mine = out / "helpdesk_mcp" / "tools" / "admin.py"
        mine.write_text("# my own admin tools, registered from server.py\n", encoding="utf-8")
        before = _snapshot(out)
        with pytest.raises(MCPcastError) as info:
            write_project(_plan(profile=SafetyProfile.FULL), out)  # the plan gains admin
        assert str(info.value).startswith(
            "helpdesk_mcp/tools/admin.py exists and was not generated by mcpcast — rename it"
        )
        assert "--force" in str(info.value)
        assert _snapshot(out) == before  # atomic: nothing else was written either
        write_project(_plan(profile=SafetyProfile.FULL), out, force=True)
        assert mine.read_text(encoding="utf-8").startswith(
            '"""Tools for admin — generated from mcpcast.plan.yaml.'
        )

    def test_replaced_tools_init_is_refused_too(self, tmp_path):
        out = tmp_path / "helpdesk-mcp"
        write_project(_plan(), out)
        init = out / "helpdesk_mcp" / "tools" / "__init__.py"
        init.write_text("MODULES = ()\n", encoding="utf-8")
        with pytest.raises(MCPcastError, match="helpdesk_mcp/tools/__init__.py exists and was"):
            write_project(_plan(), out)
        assert init.read_text(encoding="utf-8") == "MODULES = ()\n"

    def test_several_foreign_modules_are_all_named(self, tmp_path):
        out = tmp_path / "helpdesk-mcp"
        write_project(_plan(profile=SafetyProfile.READ_ONLY), out)
        tools = out / "helpdesk_mcp" / "tools"
        (tools / "admin.py").write_text("# mine\n", encoding="utf-8")
        (tools / "tickets.py").write_text("# also mine now\n", encoding="utf-8")
        with pytest.raises(MCPcastError) as info:
            write_project(_plan(profile=SafetyProfile.FULL), out)
        assert str(info.value).startswith(
            "helpdesk_mcp/tools/admin.py, helpdesk_mcp/tools/tickets.py exist and were not "
            "generated by mcpcast"
        )

    def test_copied_generated_module_under_another_name_is_kept(self, tmp_path):
        out = tmp_path / "helpdesk-mcp"
        write_project(_plan(profile=SafetyProfile.FULL), out)
        tools = out / "helpdesk_mcp" / "tools"
        copy = tools / "my_tickets.py"
        copy.write_text(
            (tools / "tickets.py").read_text(encoding="utf-8") + "\n# my additions\n",
            encoding="utf-8",
        )
        assert _GENERATED_MARKER in copy.read_text(
            encoding="utf-8"
        )  # carries the header of tickets.py
        assert _is_generated(copy) and not _is_generated(copy, "my_tickets")
        write_project(_plan(profile=SafetyProfile.READ_ONLY), out)  # admin.py goes, the copy stays
        assert not (tools / "admin.py").exists()
        assert copy.read_text(encoding="utf-8").endswith("# my additions\n")

    def test_copy_at_a_path_the_plan_gains_is_refused(self, tmp_path):
        out = tmp_path / "helpdesk-mcp"
        write_project(_plan(profile=SafetyProfile.READ_ONLY), out)
        tools = out / "helpdesk_mcp" / "tools"
        (tools / "admin.py").write_text(
            (tools / "tickets.py").read_text(encoding="utf-8"), encoding="utf-8"
        )  # header says tickets
        with pytest.raises(MCPcastError, match="helpdesk_mcp/tools/admin.py exists and was not"):
            write_project(_plan(profile=SafetyProfile.FULL), out)

    def test_marker_outside_the_module_docstring_does_not_count(self, tmp_path):
        out = tmp_path / "helpdesk-mcp"
        write_project(_plan(profile=SafetyProfile.FULL), out)
        tools = out / "helpdesk_mcp" / "tools"
        note = tools / "notes.py"
        note.write_text(
            f'"""Mine."""\n\nWHY = "{_GENERATED_MARKER} was the template"\n', encoding="utf-8"
        )
        no_docstring = tools / "helpers.py"
        no_docstring.write_text(f"# {_GENERATED_MARKER}\nX = 1\n", encoding="utf-8")
        assert not _is_generated(note) and not _is_generated(no_docstring)
        write_project(_plan(profile=SafetyProfile.READ_ONLY), out)
        assert note.exists() and no_docstring.exists()

    def test_stale_module_with_eighty_tools_is_removed(self, tmp_path):
        """The header sits before the per-tool listing, so a long module is still ours."""
        out = tmp_path / "warehouse-mcp"
        write_project(mcpcast(_many_tools_spec("things", 80), name="warehouse"), out)
        things = out / "warehouse_mcp" / "tools" / "things.py"
        text = things.read_text(encoding="utf-8")
        assert text.index(_GENERATED_MARKER) < 400 < 4096 < text.index('"""', 3)
        assert _is_generated(things, "things")
        write_project(mcpcast(_many_tools_spec("items", 80), name="warehouse"), out)
        listing = sorted(p.name for p in (out / "warehouse_mcp" / "tools").glob("*.py"))
        assert listing == ["__init__.py", "items.py"]
        names = {t.name for t in load_generated_server(out).server._tool_registry.list_all()}
        assert len(names) == 80 and all(n.startswith("list_items_kind") for n in names)

    def test_renamed_api_name_is_refused_and_names_the_scaffold(self, tmp_path):
        out = tmp_path / "proj"
        write_project(mcpcast(SPEC, name="pet-api-key"), out)
        assert 'name = "pet-api-key-mcp"' in (out / "pyproject.toml").read_text(encoding="utf-8")
        before = _snapshot(out)
        with pytest.raises(MCPcastError) as info:
            write_project(mcpcast(SPEC, name="petshop"), out, write_plan=False)
        message = str(info.value)
        assert "already holds the generated package pet_api_key_mcp/" in message
        assert "api.name 'petshop' maps to petshop_mcp/" in message
        assert "pyproject.toml (name, [project.scripts], packages include)" in message
        assert "Dockerfile (COPY, CMD)" in message
        assert "Delete pet_api_key_mcp/, pyproject.toml and Dockerfile and regenerate" in message
        assert "new --out directory" in message and "--force" in message
        assert _snapshot(out) == before
        assert not (out / "petshop_mcp").exists()

    def test_renamed_api_name_without_scaffold_and_with_force(self, tmp_path):
        out = tmp_path / "proj"
        write_project(mcpcast(SPEC, name="pet-api-key"), out)
        (out / "pyproject.toml").unlink()
        (out / "Dockerfile").unlink()
        with pytest.raises(MCPcastError) as info:
            write_project(mcpcast(SPEC, name="petshop"), out)
        assert "Delete pet_api_key_mcp/ and regenerate, or generate into a new --out" in str(
            info.value
        )
        assert "pyproject.toml" not in str(info.value)
        write_project(mcpcast(SPEC, name="petshop"), out, force=True)
        assert (out / "petshop_mcp" / "__init__.py").exists()
        assert (out / "pet_api_key_mcp" / "__init__.py").exists()  # left to the developer
        assert 'name = "petshop-mcp"' in (out / "pyproject.toml").read_text(
            encoding="utf-8"
        )  # recreated

    def test_a_package_that_is_not_ours_is_not_a_stale_package(self, tmp_path):
        out = tmp_path / "proj"
        write_project(mcpcast(SPEC, name="petshop"), out)
        other = out / "legacy_mcp"
        other.mkdir()
        (other / "__init__.py").write_text(
            '"""A hand-written package that happens to end in _mcp."""\n',
            encoding="utf-8",
        )
        write_project(mcpcast(SPEC, name="petshop"), out)  # not refused
        assert (other / "__init__.py").exists()

    def test_readme_states_the_ownership_rules(self):
        md = render_readme(_plan())
        row = next(
            line for line in md.splitlines() if line.startswith("| `helpdesk_mcp/tools/*.py`")
        )
        assert "a file without the generated header" in row and "regeneration refuses" in row
        plan_row = next(
            line for line in md.splitlines() if line.startswith("| `mcpcast.plan.yaml`")
        )
        assert "`api.name` fixes the package (`helpdesk_mcp/`)" in plan_row
        assert "`helpdesk-mcp` command" in plan_row and "is refused" in plan_row


# ---------------------------------------------------------------------------
# README client snippets: M8
# ---------------------------------------------------------------------------


def _connect_section(md: str) -> str:
    return md[md.index("## Connect an AI") : md.index("## Tools")]


def _snippet_call(section: str, cls: str) -> str:
    """The one ``cls(...)`` call in the Promptise snippet — balanced parentheses."""
    start = section.index(f"{cls}(") + len(cls)
    depth, end = 0, start
    for end, char in enumerate(section[start:], start):
        depth += (char == "(") - (char == ")")
        if depth == 0:
            break
    return cls + section[start : end + 1]


class TestClientSnippetsMatchAuthMode:
    def test_env_token_snippets_all_carry_the_credential(self):
        section = _connect_section(render_readme(_plan(auth=AuthMode.ENV_TOKEN)))
        assert "does not inherit your shell" in section
        assert (
            section.count('"env": {"MCPCAST_UPSTREAM_TOKEN": "Bearer <your API token>"}') == 2
        )  # Claude Desktop and Cursor
        assert (
            'claude mcp add helpdesk -e MCPCAST_UPSTREAM_TOKEN="Bearer <your API token>" -- python'
            in section
        )
        assert 'env={"MCPCAST_UPSTREAM_TOKEN": "Bearer <your API token>"}' in section
        spec = eval(_snippet_call(section, "StdioServerSpec"), {"StdioServerSpec": StdioServerSpec})
        assert spec.env == {"MCPCAST_UPSTREAM_TOKEN": "Bearer <your API token>"}
        assert spec.command == "python" and spec.args == ["server.py"]
        assert "HTTPServerSpec" not in section

    @pytest.mark.parametrize(
        ("auth", "header", "value", "kwarg", "secret"),
        [
            (AuthMode.API_KEY, "x-api-key", "<key>", "api_key", "<key>"),
            (AuthMode.PASSTHROUGH, "Authorization", "Bearer <token>", "bearer_token", "<token>"),
        ],
        ids=["api-key", "passthrough"],
    )
    def test_header_modes_get_http_snippets_and_no_stdio_config(
        self, auth, header, value, kwarg, secret
    ):
        section = _connect_section(render_readme(_plan(auth=auth)))
        assert f"needs an `{header}` header on every request" in section
        assert "StdioServerSpec" not in section and "/absolute/path/to/server.py" not in section
        assert "python server.py --transport http" in section
        assert (
            f"claude mcp add helpdesk --transport http http://127.0.0.1:8080/mcp "
            f'--header "{header}: {value}"' in section
        )
        assert (
            f'"helpdesk": {{ "url": "http://127.0.0.1:8080/mcp", "headers": {{ "{header}": "{value}" }} }}'
            in section
        )
        assert "`claude_desktop_config.json` has no header field for HTTP servers" in section
        call = _snippet_call(section, "HTTPServerSpec")
        assert call == f'HTTPServerSpec(url="http://127.0.0.1:8080/mcp", {kwarg}="{secret}")'
        spec = eval(call, {"HTTPServerSpec": HTTPServerSpec})  # the snippet is a real spec
        assert spec.url == "http://127.0.0.1:8080/mcp"
        assert getattr(spec, kwarg).get_secret_value() == secret

    def test_none_snippets_stay_plain_stdio(self):
        section = _connect_section(render_readme(_plan(auth=AuthMode.NONE)))
        assert "claude mcp add helpdesk -- python /absolute/path/to/server.py" in section
        assert (
            '"env"' not in section and "HTTPServerSpec" not in section and "header" not in section
        )
        assert 'StdioServerSpec(command="python", args=["server.py"])' in section

    def test_passthrough_claims_only_the_current_request(self):
        md = render_readme(_plan(auth=AuthMode.PASSTHROUGH))
        assert "every agent acts with its own user's permissions" not in md
        assert "a call acts with the caller's credential on that request" in md


# ---------------------------------------------------------------------------
# Plain-http upstreams: M10 (README and conftest)
# ---------------------------------------------------------------------------


def _plain_http_spec() -> dict:
    spec = {
        "openapi": "3.0.0",
        "info": {"title": "Intranet"},
        "servers": [{"url": "http://api.intranet.corp:8080"}],
        "paths": {
            "/ping": {"get": {"operationId": "ping"}},
            "/legacy": {
                "get": {
                    "operationId": "legacyPing",
                    "servers": [{"url": "http://legacy.example.test"}],
                }
            },
        },
    }
    return spec


class TestPlainHttpProjects:
    @pytest.mark.parametrize("auth", [AuthMode.ENV_TOKEN, AuthMode.API_KEY, AuthMode.PASSTHROUGH])
    def test_conftest_lifts_the_guard_and_names_the_hosts(self, auth):
        files = render_project(mcpcast(_plain_http_spec(), name="intranet", auth=auth))
        conftest = files["tests/conftest.py"]
        assert 'monkeypatch.setattr("intranet_mcp.upstream.ALLOW_INSECURE_HTTP", True)' in conftest
        comment = " ".join(
            line.strip("# ") for line in conftest.splitlines() if line.startswith("    # ")
        )
        assert "plain http (api.intranet.corp:8080, legacy.example.test)" in comment
        assert "MCPCAST_ALLOW_INSECURE_HTTP=1" in conftest
        assert all(len(line) <= 100 for line in conftest.splitlines())
        readme = files["README.md"]
        assert (
            "**The upstream is plain `http://` (`api.intranet.corp:8080`, `legacy.example.test`).**"
            in readme
        )
        assert "`MCPCAST_ALLOW_INSECURE_HTTP=1`" in readme and "`UPSTREAM_INSECURE`" in readme

    def test_https_and_credential_free_projects_keep_the_guard(self):
        https = render_project(_plan(auth=AuthMode.ENV_TOKEN))
        assert "ALLOW_INSECURE_HTTP" not in https["tests/conftest.py"]
        assert "The upstream is plain" not in https["README.md"]
        none = render_project(mcpcast(_plain_http_spec(), name="intranet", auth=AuthMode.NONE))
        assert "ALLOW_INSECURE_HTTP" not in none["tests/conftest.py"]  # no credential travels
        assert "The upstream is plain" not in none["README.md"]


# ---------------------------------------------------------------------------
# Generated tests compare the wire path: M16
# ---------------------------------------------------------------------------


class TestGeneratedPathAssertions:
    def test_tests_compare_the_percent_encoded_path(self):
        spec = {
            "openapi": "3.0.0",
            "info": {"title": "Directory"},
            "servers": [{"url": "https://dir.example"}],
            "paths": {
                "/users/{email}": {
                    "get": {
                        "operationId": "getUser",
                        "parameters": [
                            {
                                "name": "email",
                                "in": "path",
                                "required": True,
                                "schema": {"type": "string", "format": "email"},
                            }
                        ],
                    }
                }
            },
        }
        files = render_project(mcpcast(spec, name="directory", auth=AuthMode.NONE))
        conftest, tests = files["tests/conftest.py"], files["tests/test_tools.py"]
        assert "def path_of(request: httpx.Request) -> str:" in conftest
        assert 'return request.url.raw_path.split(b"?", 1)[0].decode()' in conftest
        assert "from conftest import FakeUpstream, error_of, path_of" in tests
        assert 'assert path_of(upstream.last) == "/users/ada%40example.com"' in tests
        assert "upstream.last.url.path" not in tests


# ---------------------------------------------------------------------------
# The emitted route local never shadows a parameter: M19
# ---------------------------------------------------------------------------


class TestRouteLocal:
    def test_handler_local_is_underscored(self):
        src = render_project(_plan())["helpdesk_mcp/tools/tickets.py"]
        assert '        _route = select_route(ROUTES["list_tickets"], args)' in src
        assert "        return await upstream.call(_route, args, ctx)" in src
        assert re.search(r"^\s+route = ", src, re.M) is None


# ---------------------------------------------------------------------------
# Description caps: M23
# ---------------------------------------------------------------------------


def _bloated_spec() -> dict:
    return {
        "openapi": "3.0.0",
        "info": {"title": "Bloat"},
        "servers": [{"url": "https://bloat.example"}],
        "paths": {
            "/things": {
                "post": {
                    "operationId": "makeThing",
                    "summary": "Make a thing",
                    "requestBody": {
                        "required": True,
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "required": ["kind", "blob"],
                                    "properties": {
                                        "kind": {
                                            "type": "string",
                                            "description": "k" * 5000,
                                            "enum": [f"{i:03d}-" + "v" * 500 for i in range(50)],
                                        },
                                        "blob": {"type": "string", "example": "b" * 100_000},
                                        **{
                                            f"field_{i:03d}": {
                                                "type": "string",
                                                "description": "word " * 100,
                                            }
                                            for i in range(200)
                                        },
                                    },
                                }
                            }
                        },
                    },
                }
            }
        },
    }


class TestDescriptionCaps:
    def test_hostile_spec_stays_within_the_cap(self):
        plan = mcpcast(
            _bloated_spec(), name="bloat", profile=SafetyProfile.FULL, auth=AuthMode.NONE
        )
        tool = plan.tool("make_thing")
        assert len(tool.example["blob"]) == 100_000  # the plan keeps the full text
        assert len(tool.params["kind"].description) == 5000
        text = _tool_description(tool, _signature(tool)[2])
        assert len(text) <= _MAX_DESCRIPTION_CHARS
        example = next(line for line in text.splitlines() if line.startswith("Example: "))
        assert len(example) <= len("Example: ") + _MAX_EXAMPLE_CHARS and example.endswith("…")
        kind = next(line for line in text.splitlines() if line.startswith("  - kind "))
        assert "k" * _MAX_PARAM_DESC_CHARS not in kind and "k" * 500 + "…" in kind
        assert "one of: 000-" + "v" * 55 + "…, 001-" in kind and " … (+38 more)" in kind
        assert re.search(r"^  … and \d+ more parameters \(see the input schema\)$", text, re.M)
        assert text.count("\n  - field_") < 200
        assert clipped_descriptions(plan) == ["make_thing"]
        src = render_project(plan)["bloat_mcp/tools/things.py"]
        assert "b" * 2000 not in src  # nothing above the cap reaches the module either

    def test_ordinary_descriptions_are_untouched(self):
        plan = _plan(profile=SafetyProfile.FULL)
        assert clipped_descriptions(plan) == []
        tool = plan.tool("create_ticket")
        text = _tool_description(tool, _signature(tool)[2])
        assert "…" not in text and "more parameters" not in text
        assert "  - subject (string, required)" in text

    def test_enum_beyond_twelve_entries_is_counted_not_clipped(self):
        spec = {
            "openapi": "3.0.0",
            "info": {"title": "Flags"},
            "servers": [{"url": "https://f.example"}],
            "paths": {
                "/flags": {
                    "get": {
                        "operationId": "listFlags",
                        "parameters": [
                            {
                                "name": "colour",
                                "in": "query",
                                "schema": {"type": "string", "enum": [f"c{i}" for i in range(15)]},
                            }
                        ],
                    }
                }
            },
        }
        plan = mcpcast(spec, name="flags", auth=AuthMode.NONE)
        tool = plan.tool("list_flags")
        text = _tool_description(tool, _signature(tool)[2])
        assert "one of: c0, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11 … (+3 more)" in text
        assert clipped_descriptions(plan) == []  # a long enum is expected; nothing was cut


# ---------------------------------------------------------------------------
# Markdown escaping of plan-only text: L3
# ---------------------------------------------------------------------------


class TestReadmeEscapesPlanText:
    def test_dropped_ids_and_hidden_defaults_are_code_spans(self):
        plan = _plan(profile=SafetyProfile.FULL)
        hostile_id = "x` | [phish](https://evil.test/login) <img src=x onerror=alert(1)> `"
        tool = plan.tool("create_ticket")
        params = dict(tool.params)
        params["mode`[phish](https://evil.test)`"] = ParamPlan(
            hidden=True, default="[img](https://evil.test/x) <img src=y>"
        )
        plan = plan.model_copy(
            update={
                "dropped": [
                    *plan.dropped,
                    DroppedOp.model_construct(operation_id=hostile_id, reason="hand-edited"),
                ],
                "tools": [
                    t.model_copy(update={"params": params}) if t is tool else t for t in plan.tools
                ],
            }
        )
        md = render_readme(plan)
        prose = re.sub(r"``.*?``|`[^`\n]*`", "", md)  # code spans render literally anyway
        assert "evil.test" not in prose and "<img" not in prose  # no live link, no tag
        assert "](https://docs.promptise.com" in prose  # the README's own link is untouched
        assert "hand-edited" in md and "always sends" in md
        assert "onerror=alert(1)" in md and "[img](https://evil.test/x)" in md  # shown, inert


# ---------------------------------------------------------------------------
# Identifier length: L5
# ---------------------------------------------------------------------------


class TestIdentifierCap:
    def test_long_names_are_cut_with_the_suffix_inside_the_cap(self):
        long = "customer_account_" + "x" * 80
        assert len(long) > _MAX_IDENT_CHARS
        ident = python_identifier(long)
        assert ident == long[:_MAX_IDENT_CHARS] and len(ident) == _MAX_IDENT_CHARS
        taken: set[str] = set()
        first = python_identifier(long, taken)
        second = python_identifier(long + "_y", taken)  # the same once cut: made unique
        assert first == ident and second == long[: _MAX_IDENT_CHARS - 2] + "_2"
        assert len(second) == _MAX_IDENT_CHARS
        assert python_identifier("from", taken) == "from_"  # short names: as before
        assert python_identifier("from", taken) == "from__2"

    def test_cut_names_are_still_checked_for_reserved_prefixes(self):
        assert python_identifier("model_" + "x" * 80) == "model_" + "x" * 50 + "_"
        assert python_identifier("a" * 55 + "_" + "b" * 20) == "a" * 55  # no dangling underscore
        assert python_identifier("short-name") == "short_name"


# ---------------------------------------------------------------------------
# The CLI summary line: L16
# ---------------------------------------------------------------------------


class TestDescribeWritten:
    def test_relative_output_directory_is_broken_down_by_area(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        written = write_project(_plan(), "rel-dir")
        modules = sum(1 for path in written if "helpdesk_mcp" in path.parts)
        assert modules >= 9  # six package modules, tools/__init__.py, two tools modules
        summary = describe_written(written, "rel-dir")
        assert summary.startswith(f"helpdesk_mcp/ ({modules} modules), tests/ (2), ")
        assert "mcpcast.plan.yaml" in summary and "README.md" in summary
        assert "rel-dir" not in summary
        assert describe_written(written, tmp_path / "rel-dir") == summary  # absolute root, same

    def test_paths_from_elsewhere_are_shown_as_they_are(self, tmp_path):
        elsewhere = Path("/elsewhere/server.py")
        summary = describe_written([elsewhere], tmp_path / "proj")
        assert summary == str(elsewhere)  # shown as the platform spells it


# ---------------------------------------------------------------------------
# Regression from the emit tests this file narrows: the normal regeneration path
# ---------------------------------------------------------------------------


class TestRegenerationStillWorks:
    def test_in_place_regeneration_over_own_files_needs_no_force(self, tmp_path):
        out = tmp_path / "helpdesk-mcp"
        write_project(_plan(profile=SafetyProfile.STANDARD, auth=AuthMode.ENV_TOKEN), out)
        (out / "helpdesk_mcp" / "tools" / "tickets.py").write_text(
            (out / "helpdesk_mcp" / "tools" / "tickets.py").read_text(encoding="utf-8")
            + "\n# edited\n",
            encoding="utf-8",
        )  # still ours: the header is intact
        write_project(
            _plan(profile=SafetyProfile.FULL, auth=AuthMode.ENV_TOKEN), out, write_plan=False
        )
        assert "# edited" not in (out / "helpdesk_mcp" / "tools" / "tickets.py").read_text(
            encoding="utf-8"
        )
        names = {t.name for t in load_generated_server(out).server._tool_registry.list_all()}
        assert {"list_tickets", "create_ticket", "get_customer", "purge_all"} <= names


# ---------------------------------------------------------------------------
# The README states what the generated runtime does: keys, credential slot, .env, base URL
# ---------------------------------------------------------------------------


def _spec_with_scheme(scheme: dict) -> dict:
    return {
        **SPEC,
        "components": {"securitySchemes": {"main": scheme}},
        "security": [{"main": []}],
    }


class TestReadmeFollowsTheRuntime:
    def test_api_key_readme_mints_keys_and_ships_no_documentation_key(self):
        md = render_readme(
            _plan(profile=SafetyProfile.FULL, auth=AuthMode.API_KEY, approval=ApprovalMode.PENDING)
        )
        exports = [
            line for line in md.splitlines() if line.startswith("export MCPCAST_CLIENT_KEYS=")
        ]
        assert len(exports) == 2  # the auth section and the pending-approval section
        assert all('"sk-acme"' not in line and '"sk-reviewer"' not in line for line in exports)
        assert '"sk-<generated>": {"client_id": "acme-agent"' in exports[0]
        assert '"sk-<agent key>"' in exports[1] and '"sk-<reviewer key>"' in exports[1]
        assert (
            md.count("python -c 'import secrets; print(\"sk-\" + secrets.token_urlsafe(32))'") == 2
        )
        assert "refuses to start with no key, with a `<placeholder>` key or with a key copied" in md
        assert "placeholder (`<…>`) and documentation keys are refused" in md

    @pytest.mark.parametrize(
        ("scheme", "slot", "value"),
        [
            (
                {"type": "http", "scheme": "bearer"},
                "the `Authorization` header",
                "Bearer <your API token>",
            ),
            (
                {"type": "apiKey", "in": "header", "name": "X-API-Key"},
                "the `X-API-Key` header",
                "<your API key>",
            ),
            (
                {"type": "apiKey", "in": "query", "name": "api_key"},
                "the `api_key` query parameter",
                "<your API key>",
            ),
        ],
        ids=["bearer", "header-key", "query-key"],
    )
    def test_credential_slot_comes_from_the_spec(self, scheme, slot, value):
        spec = _spec_with_scheme(scheme)
        env_token = render_readme(mcpcast(spec, name="helpdesk", auth=AuthMode.ENV_TOKEN))
        assert f"presents one credential from the environment, sent as {slot}" in env_token
        assert f"export MCPCAST_UPSTREAM_TOKEN='{value}'" in env_token
        assert f'"env": {{"MCPCAST_UPSTREAM_TOKEN": "{value}"}}' in env_token  # client snippets too
        assert f'env={{"MCPCAST_UPSTREAM_TOKEN": "{value}"}}' in env_token
        assert (
            f"| `MCPCAST_UPSTREAM_TOKEN` | `env-token` mode: the value sent upstream as {slot}"
            in env_token
        )
        api_key = render_readme(mcpcast(spec, name="helpdesk", auth=AuthMode.API_KEY))
        assert f"each tenant has its own upstream credential, sent as {slot}" in api_key
        assert f'export MCPCAST_UPSTREAM_TOKENS=\'{{"acme": "{value}"}}\'' in api_key
        assert f"each tenant's upstream credential, sent as {slot}, read per call" in api_key

    def test_env_file_base_url_and_excerpt_rows_match_the_runtime(self):
        md = render_readme(_plan(auth=AuthMode.ENV_TOKEN))
        assert (
            "Copy `.env.example` to `.env` next to `server.py` and fill it in: `python server.py`,\n"
            "`python -m helpdesk_mcp` and `helpdesk-mcp` read it at start-up" in md
        )
        assert "`PROMPTISE_NO_DOTENV=1` skips the file" in md
        assert "or in `.env` next to `server.py`:" in md  # the env-token section points at it
        base_url = next(
            line for line in md.splitlines() if line.startswith("| `MCPCAST_BASE_URL` |")
        )
        assert (
            "One clean URL: no `user:password@`, query string or fragment (refused at start-up)"
            in base_url
        )
        excerpt = next(
            line for line in md.splitlines() if line.startswith("| `MCPCAST_ERROR_EXCERPT_CHARS` |")
        )
        assert "the credential is scrubbed to `[redacted]` before the excerpt is cut" in excerpt
